/* The picture, table and exported record all use DesignModel results. */
(function(){'use strict';
const M=window.DesignModel,$=id=>document.getElementById(id),modes=['modular','algorithmic','procedural','parametric'];
const defaults={modular:{cols:4,rows:3,panelW_mm:600,panelD_mm:600,joint_mm:20},algorithmic:{length_m:6,step_m:1.6,includeEnd:true},procedural:{cols:4,rows:3,seed:42,openFraction:.4},parametric:{width_m:6,depth_m:4,baysX:3,baysY:2,thickness_mm:80}};
const fields={modular:[['cols','Columns','Kolone',1,10,1],['rows','Rows','Redovi',1,8,1],['panelW_mm','Panel width / mm','Širina panela / mm',100,3000,'any'],['panelD_mm','Panel depth / mm','Dubina panela / mm',100,3000,'any'],['joint_mm','Joint width / mm','Širina spoja / mm',0,150,'any']],algorithmic:[['length_m','Line length / m','Dužina linije / m',1,20,'any'],['step_m','Chosen step / m','Izabrani korak / m',.25,5,'any']],procedural:[['cols','Columns','Kolone',1,10,1],['rows','Rows','Redovi',1,8,1],['seed','Seed / uint32','Seme / uint32',0,4294967295,1],['openFraction','Opening threshold / 0–1','Prag otvaranja / 0–1',0,1,'any']],parametric:[['width_m','Width / m','Širina / m',1,24,'any'],['depth_m','Depth / m','Dubina / m',1,20,'any'],['baysX','Bays along X','Polja duž X',1,10,1],['baysY','Bays along Y','Polja duž Y',1,8,1],['thickness_mm','Sheet thickness / mm','Debljina ploče / mm',10,500,'any']]};
let lang='en';const state={mode:modes.includes(location.hash.slice(1))?location.hash.slice(1):'modular',data:JSON.parse(JSON.stringify(defaults)),active:0,rows:[],valid:true,result:null};
const W={en:{
 titles:['Parts and joints','A rule along an edge','A repeatable variation','A chain of dependencies'],
 questions:['What changes when a joint is included between repeated parts?','Place stations at a chosen step. Decide explicitly whether to add the far endpoint.','Keep the grid and rule. Change a seed or threshold and inspect the variation.','Change one dimension and follow its consequences through spans, area and nominal volume.'],
 boundaries:['A plan of rectangular panels and interior joints. There is no joint outside the outermost panels. Joint area is the uncovered footprint, not a material or waterproofing specification.','This is a deterministic placement rule, not an optimal spacing or a support design. The optional far endpoint is an extra rule; regular steps alone may stop before it. Near-integer quotients use a tolerance of 8 × machine epsilon × max(1, |L/s|). The same snap decision sets the last coordinate exactly to L.','Open and closed are geometric states. The threshold is not a guaranteed opening ratio in a finite grid. This 32-bit linear congruential sequence is a teaching choice, not cryptographic randomness. No daylight, thermal, acoustic or structural performance is predicted.','A nominal rectangular canopy with a uniform solid sheet. Grid intersections are coordinates, not verified supports. No member sizing, loads, deflection, connections, openings, waste or material behaviour is calculated.'],
 architecture:['Keep 12 panels while changing their proportions. Compare the footprint with and without joints. Explain which relationship makes the composition feel different.','Compare a facade rhythm with the endpoint option on and off. Draw the final interval and explain why it differs. Would a different rule serve your intention?','Keep one seed and compare three thresholds. Then keep the threshold and change the seed. Describe repetition, openings and rhythm without claiming better environmental performance.','Keep 24 m² while changing width and depth. Which proportions and grid spacings change? Which nominal quantities remain the same?'],
 civil:['Account for all panel area and joint footprint. Test whether doubling every length multiplies each area by four. These are geometric quantities, not a construction takeoff.','List station coordinates and intervals. Check the sum of intervals against covered length. Distinguish a layout rule from the calculations needed to choose real supports.','Reproduce a saved parameter record. Check that every integer state and opening is identical. Then explain why a changed generator or iteration order can change the result.','Refine the grid while keeping the envelope and thickness. Check area and volume invariance. List what information is still missing for any structural calculation.'],
 includeEnd:'Add the endpoint at L',seedNext:'Seed +1 →',noRandom:'No hidden randomness. The same version, seed, parameters and row order reproduce this sequence.',range:'Supported range',invalid:'No result. Fill every field with a finite value in its displayed range. Grid counts and the seed must be integers.',row:'row',yes:'yes',no:'no',open:'open',closed:'closed',step:'step',endpoint:'endpoint',width:'Overall width',depth:'Overall depth',panels:'Panels',jointArea:'Joint footprint',stations:'Stations',chosenStep:'Chosen step',remainder:'Remainder after full steps',endpointIncluded:'Far endpoint included',openPanels:'Open panels',actualRatio:'Actual opening ratio',threshold:'Threshold',seed:'Seed',area:'Plan area',volume:'Nominal solid volume',spans:'Grid spacings X × Y',nodes:'Grid intersections',id:'ID',copied:'Calculation function copied.',copyFailed:'Clipboard unavailable. The code is selected; copy it using your device.',exported:'JSON prepared for local download.',exportFailed:'The local download could not be prepared.',title:'One system, four ways · OR',noteMod:'The footprint includes panels and joints.',noteAlg:'Dark marks are generated stations. The outlined far endpoint is the optional extra rule.',noteProc:'Filled panels are closed; empty panels are open. The heavy outline follows the selected row.',notePar:'Lines and points are the parameter-derived grid; the highlighted point follows the selected row.'
},sr:{
 titles:['Delovi i spojevi','Pravilo duž ivice','Ponovljiva varijacija','Lanac zavisnosti'],
 questions:['Šta se menja kada između ponovljenih delova uključimo spoj?','Postavi stanice izabranim korakom. Posebno odluči da li dodaješ krajnju tačku.','Zadrži mrežu i pravilo. Promeni seme ili prag i pregledaj varijaciju.','Promeni jednu meru i prati posledice kroz razmake mreže, površinu i nominalnu zapreminu.'],
 boundaries:['Plan pravougaonih panela i unutrašnjih spojeva. Izvan krajnjih panela nema dodatnog spoja. Površina spojeva je nepokriven deo osnove, ne specifikacija materijala ili hidroizolacije.','Ovo je determinističko pravilo postavljanja, ne optimalan razmak ili projekat oslonaca. Krajnja tačka je dodatno pravilo; redovni koraci ne moraju stići do nje. Količnik blizu celog broja koristi toleranciju 8 × mašinski epsilon × max(1, |L/s|). Ista odluka postavlja poslednju koordinatu tačno na L.','Otvoreno i zatvoreno su geometrijska stanja. Prag ne garantuje tačan udeo otvora u konačnoj mreži. Ovaj 32-bitni linearni kongruentni niz je nastavni izbor, ne kriptografska slučajnost. Ne predviđa osvetljenje, toplotu, akustiku ili nosivost.','Nominalna pravougaona nadstrešnica sa ravnomernom punom pločom. Preseci mreže su koordinate, ne provereni oslonci. Ne računaju se dimenzionisanje elemenata, opterećenja, ugib, veze, otvori, otpad ni ponašanje materijala.'],
 architecture:['Zadrži 12 panela, a menjaj proporcije. Uporedi osnovu sa spojevima i bez njih. Objasni koji odnos menja doživljaj kompozicije.','Uporedi ritam fasade sa dodatom krajnjom tačkom i bez nje. Nacrtaj poslednji razmak i objasni razliku. Da li bi neko drugo pravilo bolje izrazilo tvoju nameru?','Sa jednim semenom uporedi tri praga. Zatim zadrži prag, a promeni seme. Opiši ponavljanje, otvore i ritam bez tvrdnje o boljim fizičkim performansama.','Zadrži 24 m², a menjaj širinu i dubinu. Koje proporcije i razmaci se menjaju? Koje nominalne količine ostaju iste?'],
 civil:['Obračunaj površinu panela i nepokrivenih spojeva. Proveri da li udvostručavanje svih dužina množi površine sa četiri. To su geometrijske količine, ne građevinski predmer.','Popiši koordinate stanica i razmake. Uporedi zbir razmaka sa pokrivenom dužinom. Razdvoji pravilo rasporeda od proračuna potrebnih za izbor stvarnih oslonaca.','Ponovi sačuvan zapis parametara. Proveri svaki celobrojni izlaz i otvor. Objasni zašto promena generatora ili redosleda obilaska može promeniti rezultat.','Usitni mrežu uz iste spoljne mere i debljinu. Proveri da površina i zapremina ostaju iste. Navedi šta još nedostaje za bilo kakav proračun konstrukcije.'],
 includeEnd:'Dodaj krajnju tačku na L',seedNext:'Seme +1 →',noRandom:'Nema skrivene slučajnosti. Ista verzija, seme, parametri i redosled redova ponavljaju ovaj niz.',range:'Podržan opseg',invalid:'Nema rezultata. Svako polje mora imati konačan broj u označenom opsegu. Brojevi polja mreže i seme moraju biti celi.',row:'red',yes:'da',no:'ne',open:'otvoreno',closed:'zatvoreno',step:'korak',endpoint:'kraj',width:'Ukupna širina',depth:'Ukupna dubina',panels:'Paneli',jointArea:'Površina spojeva',stations:'Stanice',chosenStep:'Izabrani korak',remainder:'Ostatak posle punih koraka',endpointIncluded:'Krajnja tačka uključena',openPanels:'Otvoreni paneli',actualRatio:'Stvarni udeo otvora',threshold:'Prag',seed:'Seme',area:'Površina osnove',volume:'Nominalna puna zapremina',spans:'Razmaci mreže X × Y',nodes:'Preseci mreže',id:'ID',copied:'Računska funkcija je kopirana.',copyFailed:'Ostava nije dostupna. Kod je označen; kopiraj ga na uređaju.',exported:'JSON je pripremljen za lokalno preuzimanje.',exportFailed:'Lokalno preuzimanje nije pripremljeno.',title:'Jedan sistem, četiri načina · OR',noteMod:'Osnova obuhvata panele i spojeve.',noteAlg:'Tamne oznake su dobijene stanice. Oivičena krajnja tačka je opciono dodatno pravilo.',noteProc:'Popunjeni paneli su zatvoreni; prazni su otvoreni. Debeli okvir prati izabrani red.',notePar:'Linije i tačke su mreža izvedena iz parametara; označena tačka prati izabrani red.'
}};
const t=k=>W[lang][k];const fmt=n=>!Number.isFinite(n)?'—':n===0?'0':(Math.abs(n)<1e-5||Math.abs(n)>=1e7)?n.toExponential(3).replace('.',lang==='sr'?',':'.'):Number(n.toPrecision(7)).toLocaleString(lang==='sr'?'sr-Latn':'en',{maximumFractionDigits:6});
function controls(){const p=state.data[state.mode];$('controls').innerHTML=fields[state.mode].map(([key,en,sr,min,max,step])=>'<label for="p-'+key+'"><span>'+(lang==='en'?en:sr)+'</span><small>'+key+' · '+min+'–'+max+'</small><input id="p-'+key+'" data-key="'+key+'" type="number" inputmode="'+(step===1?'numeric':'decimal')+'" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(Number.isFinite(p[key])?p[key]:'')+'"></label>').join('');
if(state.mode==='algorithmic')$('controls').insertAdjacentHTML('beforeend','<label class="check"><input id="include-end" type="checkbox"'+(p.includeEnd?' checked':'')+'><span>'+t('includeEnd')+'</span></label>');
if(state.mode==='procedural')$('controls').insertAdjacentHTML('beforeend','<button id="seed-next" class="quiet" type="button">'+t('seedNext')+'</button><p class="control-note">'+t('noRandom')+'</p>');}
function read(){fields[state.mode].forEach(([key])=>state.data[state.mode][key]=$('p-'+key).valueAsNumber);if(state.mode==='algorithmic')state.data.algorithmic.includeEnd=$('include-end').checked;}
function statistics(entries){$('stats').replaceChildren(...entries.map(([label,value])=>{const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;d.append(dt,dd);return d;}));}
const NS='http://www.w3.org/2000/svg';function el(tag,a={},v){const e=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,x])=>e.setAttribute(k,String(x)));if(v!==undefined)e.textContent=v;return e;}
function txt(svg,x,y,v,anchor='start'){svg.append(el('text',{x,y,'text-anchor':anchor},v));}
function line(svg,x1,y1,x2,y2,stroke='#9aa7ae',width=1){svg.append(el('line',{x1,y1,x2,y2,stroke,'stroke-width':width}));}
function setup(width,depth){const svg=el('svg',{viewBox:'0 0 600 330',focusable:'false'});$('drawing').replaceChildren(svg);const scale=Math.min(500/width,220/depth),left=(600-width*scale)/2,top=35;return {svg,s:scale,X:x=>left+x*scale,Y:y=>top+y*scale};}
function draw(p,r){
 if(state.mode==='modular'){const {svg,s,X,Y}=setup(r.width_mm,r.depth_mm);svg.append(el('rect',{x:X(0),y:Y(0),width:r.width_mm*s,height:r.depth_mm*s,fill:'#dce2e5',stroke:'#4d5c65'}));r.panels.forEach((q,i)=>svg.append(el('rect',{x:X(q.x_mm),y:Y(q.y_mm),width:p.panelW_mm*s,height:p.panelD_mm*s,fill:i===state.active?'#2148c0':'#fffef8',stroke:'#19272d','stroke-width':i===state.active?3:1})));txt(svg,300,297,fmt(r.width_mm/1000)+' m × '+fmt(r.depth_mm/1000)+' m','middle');}
 if(state.mode==='algorithmic'){const svg=el('svg',{viewBox:'0 0 600 330',focusable:'false'});$('drawing').replaceChildren(svg);const X=x=>50+x/p.length_m*500;line(svg,50,165,550,165,'#19272d',2);line(svg,50,125,50,205);line(svg,550,125,550,205);r.points.forEach((q,i)=>{line(svg,X(q.x_m),151,X(q.x_m),179,'#19272d',2);svg.append(el('circle',{cx:X(q.x_m),cy:165,r:i===state.active?9:5,fill:q.kind==='endpoint'?'#fffef8':i===state.active?'#2148c0':'#19272d',stroke:i===state.active?'#2148c0':'#19272d','stroke-width':2}));});const selected=r.points[state.active];txt(svg,300,82,'x['+selected.i+'] = '+fmt(selected.x_m)+' m','middle');txt(svg,50,245,'0');txt(svg,550,245,'L = '+fmt(p.length_m)+' m','end');if(!p.includeEnd&&r.remainder_m>0)line(svg,X(r.last_m),188,550,188,'#2148c0',4);}
 if(state.mode==='procedural'){const {svg,s,X,Y}=setup(p.cols,p.rows);r.cells.forEach((q,i)=>{svg.append(el('rect',{x:X(q.col)+3,y:Y(q.row)+3,width:s-6,height:s-6,fill:q.open?'#fffef8':'#c3d0fa',stroke:i===state.active?'#19272d':'#2148c0','stroke-width':i===state.active?4:1}));if(!q.open)line(svg,X(q.col)+10,Y(q.row+1)-10,X(q.col+1)-10,Y(q.row)+10,'#2148c0',1);});txt(svg,300,297,p.cols+' × '+p.rows+' · '+t('seed')+' '+p.seed,'middle');}
 if(state.mode==='parametric'){const {svg,s,X,Y}=setup(p.width_m,p.depth_m);svg.append(el('rect',{x:X(0),y:Y(0),width:p.width_m*s,height:p.depth_m*s,fill:'#e4eaff',stroke:'#19272d','stroke-width':2}));for(let x=1;x<p.baysX;x++)line(svg,X(x*r.spanX_m),Y(0),X(x*r.spanX_m),Y(p.depth_m));for(let y=1;y<p.baysY;y++)line(svg,X(0),Y(y*r.spanY_m),X(p.width_m),Y(y*r.spanY_m));r.nodes.forEach((q,i)=>svg.append(el('circle',{cx:X(q.x_m),cy:Y(q.y_m),r:i===state.active?6:3,fill:i===state.active?'#2148c0':'#19272d'})));txt(svg,300,297,fmt(p.width_m)+' m × '+fmt(p.depth_m)+' m','middle');}
}
function table(head,rows){state.rows=rows;state.active=Math.min(state.active,rows.length-1);const table=document.createElement('table'),thead=document.createElement('thead'),hr=document.createElement('tr');head.forEach(v=>{const c=document.createElement('th');c.scope='col';c.textContent=v;hr.append(c);});thead.append(hr);table.append(thead);const body=document.createElement('tbody');rows.forEach((row,i)=>{const tr=document.createElement('tr');tr.dataset.row=i;if(i===state.active)tr.className='active';row.forEach((v,j)=>{const c=document.createElement(j===0?'th':'td');if(j===0)c.scope='row';c.textContent=String(v);tr.append(c);});body.append(tr);});table.append(body);$('table').replaceChildren(table);$('trace-count').textContent=t('row')+' '+(state.active+1)+' / '+rows.length;$('first').disabled=state.active===0;$('next').disabled=state.active>=rows.length-1;}
function render(){const p=state.data[state.mode];$('copy-status').textContent='';$('export-status').textContent='';$('error').hidden=true;$('code').textContent=M.codeSource(state.mode);try{
 const r=M.run(state.mode,p);state.result=r;state.valid=true;
 if(state.mode==='modular'){statistics([[t('width'),fmt(r.width_mm/1000)+' m'],[t('depth'),fmt(r.depth_mm/1000)+' m'],[t('panels'),String(r.count)],[t('jointArea'),fmt(r.jointArea_m2)+' m²']]);table([t('id'),'col / row','x / mm','y / mm'],r.panels.map(q=>[q.id,q.col+' / '+q.row,fmt(q.x_mm),fmt(q.y_mm)]));$('explanation').textContent=t('noteMod')+' '+fmt(r.panelArea_m2)+' m² + '+fmt(r.jointArea_m2)+' m² = '+fmt(r.footprint_m2)+' m².';}
 if(state.mode==='algorithmic'){statistics([[t('stations'),String(r.count)],[t('chosenStep'),fmt(p.step_m)+' m'],[t('remainder'),fmt(r.remainder_m)+' m'],[t('endpointIncluded'),t(r.last_m===p.length_m?'yes':'no')]]);table(['i','x / m','Δx / m',t('row')],r.points.map((q,i)=>[q.i,fmt(q.x_m),i?fmt(r.intervals_m[i-1]):'—',t(q.kind)]));$('explanation').textContent=t('noteAlg');}
 if(state.mode==='procedural'){statistics([[t('openPanels'),r.openCount+' / '+r.count],[t('actualRatio'),fmt(r.openRatio*100)+'%'],[t('threshold'),fmt(p.openFraction*100)+'%'],[t('seed'),String(p.seed)]]);table([t('id'),'uint32','u',lang==='en'?'state':'stanje'],r.cells.map(q=>[q.id,q.state,fmt(q.u),t(q.open?'open':'closed')]));$('explanation').textContent=t('noteProc');}
 if(state.mode==='parametric'){statistics([[t('area'),fmt(r.area_m2)+' m²'],[t('volume'),fmt(r.volume_m3)+' m³'],[t('spans'),fmt(r.spanX_m)+' × '+fmt(r.spanY_m)+' m'],[t('nodes'),String(r.nodeCount)]]);table([t('id'),'col / row','x / m','y / m'],r.nodes.map(q=>[q.id,q.col+' / '+q.row,fmt(q.x_m),fmt(q.y_m)]));$('explanation').textContent=t('notePar');}
 draw(p,r);$('export').disabled=false;
 }catch(e){state.valid=false;state.result=null;state.rows=[];$('stats').replaceChildren();$('drawing').replaceChildren();$('table').replaceChildren();$('explanation').textContent='';$('error').textContent=t('invalid');$('error').hidden=false;$('trace-count').textContent='—';$('first').disabled=$('next').disabled=$('export').disabled=true;}}
function rebuild(){document.documentElement.lang=lang==='en'?'en':'sr-Latn';document.title=t('title');document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset[lang]);$('language').textContent=lang==='en'?'SR':'EN';$('language').setAttribute('aria-label',lang==='en'?'Prikaži na srpskom':'Show in English');const i=modes.indexOf(state.mode);$('mode-number').textContent='0'+(i+1)+' / '+state.mode.toUpperCase();$('instrument-title').textContent=t('titles')[i];$('question').textContent=t('questions')[i];$('boundary').textContent=t('boundaries')[i];$('architecture-task').textContent=t('architecture')[i];$('civil-task').textContent=t('civil')[i];document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));controls();render();}
$('controls').addEventListener('submit',e=>e.preventDefault());$('controls').addEventListener('input',()=>{read();state.active=0;render();});$('controls').addEventListener('click',e=>{if(e.target.closest('button')?.id==='seed-next'){const p=state.data.procedural;if(!Number.isInteger(p.seed)||p.seed<0||p.seed>4294967295)return;p.seed=(p.seed+1)>>>0;state.active=0;controls();render();}});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;state.active=0;history.replaceState(null,'','#'+state.mode);rebuild();}));window.addEventListener('hashchange',()=>{if(modes.includes(location.hash.slice(1))){state.mode=location.hash.slice(1);state.active=0;rebuild();}});
$('language').addEventListener('click',()=>{lang=lang==='en'?'sr':'en';rebuild();});$('reset').addEventListener('click',()=>{state.data[state.mode]=JSON.parse(JSON.stringify(defaults[state.mode]));state.active=0;rebuild();});$('first').addEventListener('click',()=>{state.active=0;render();});$('next').addEventListener('click',()=>{if(state.active<state.rows.length-1)state.active++;render();const row=$('table').querySelector('.active');if(row)$('table').scrollTop=row.offsetTop-$('table').offsetTop-50;});
$('copy').addEventListener('click',async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(M.codeSource(state.mode));$('copy-status').textContent=t('copied');}catch(e){const range=document.createRange();range.selectNodeContents($('code'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);$('code').focus();$('copy-status').textContent=t('copyFailed');}});
$('export').addEventListener('click',()=>{if(!state.valid)return;try{const record=M.snapshot(state.mode,state.data[state.mode]),blob=new Blob([JSON.stringify(record,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='or-design-'+state.mode+'-v'+M.version+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('export-status').textContent=t('exported');}catch(e){$('export-status').textContent=t('exportFailed');}});
rebuild();})();
